# Aula 6: Query on wayward son - Kansas

# Para quem está com problema de instalar o postgres ou usa o colab

In [ ]:
## instale esses 3 caras, reinicie o kernel e pronto
!pip install pandas
!pip install pandasql
!pip install sqlalchemy==1.4.46

In [ ]:
## então faça upload das bases de dados ou monte o drive e está preparado o cenário!

In [4]:
import pandas as pd
import pandasql as ps
import os

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
alunos = pd.read_csv("/content/drive/MyDrive/ADA_Braskem/Curso/3-[DS-PY-006] BANCO DE DADOS I/base_curso/alunos.csv")
ps.sqldf("SELECT * FROM alunos")

,id_aluno,cpf,primeiro_nome,ultimo_nome,data_ingresso,id_cidade,endereco,numero,telefone_a,telefone_b
0,1,68740550196,abelar,henrique,2023-03-05,1,Rua da Penha,3300,866862753,274845545
1,2,34146481132,adriano,gambetta,2023-03-06,1,Rua Henrique Soares,7118,273807947,0
2,3,12728282203,amanda,moulin,2023-03-07,1,Rua Leodécio Santiago de Souza,6082,872235320,911955261
3,4,43764914607,álvaro,fonseca,2023-03-08,1,Rua Pitica,7924,938535574,262020598
4,5,23228327392,andre,melchior,2023-03-09,2,Rua Camilo Paula,4160,189494206,323561018
5,6,76360071693,antonio,zanutto,2023-03-10,2,1ª Travessa São Francisco,8932,379611062,919134470
6,7,66346021768,carolina,yumi,2023-03-11,2,Quadra SHPS Quadra 603 Conjunto 96A,5733,422505705,0
7,8,5494797137,christyan,costa,2023-03-12,2,Quadra 504 Sul Alameda 11,8070,845459713,615675266
8,9,19363011240,claudia,cavalcante,2023-03-13,3,Rua Em Projeto M,8833,202878321,603379305
9,10,5990749922,cristiane,nunes,2023-03-14,3,Travessa Júlio Veiga Mendes,9279,708729599,0
10,11,51271170337,danilo,nozima,2023-03-15,3,Rua dois,3556,374388553,328960508
11,12,18959848666,diego,rodrigues,2023-03-16,3,Rua três,1433,470084815,443097717
12,13,7562543599,emanuelle,lemos,2023-03-17,4,Rua principal,4977,326789195,0
13,14,76429831566,gabriel,mourão,2023-03-18,4,Rua São josé,4900,478176185,573145168
14,15,91204465504,haroldo,silva,2023-03-19,4,Rua santo antonio,6988,576548312,301677712
15,16,32755896447,henrique,guerrero,2023-03-20,1,Avenida brasil,8529,639795496,0
16,17,64634936082,hevans,pereira,2023-03-21,1,Avenida Brasil,4540,263674118,384972402
17,18,55207096189,isabela,bueno,2023-03-22,1,Avenida Brasilia,1185,740040561,230351268
18,19,2456915690,kelvin,pichinini,2023-03-23,1,Rua são paulo,9470,538617705,0
19,20,51865906231,lucas,voltolini,2023-03-24,5,Rua são paulo,3800,613900746,909322964
20,21,20671422357,janaina,delgado,2023-03-25,6,Rua teobaldo,9317,789048901,885432495
21,22,87486965183,manuel,castro,2023-03-26,6,rua kletemberg,582,400549536,7115358
22,23,46927680338,marcio,magrini,2023-03-27,7,rua barão tinta branca,239,466204695,23079842
23,24,17412432561,michel,souza,2023-03-28,7,tua baraão tinha uva,8347,827235134,314861183
24,25,18167196135,mike,pessanha,2023-03-29,7,rua quinze,8463,105333699,168590669
25,26,45506365798,paula,ribeiro,2023-03-30,8,rua são francisco,6572,819037434,0
26,27,11423428746,paula,marques,2023-03-31,8,rua sete de setembro,4218,730517155,0
27,28,93775321419,rafael,ribeiro,2023-04-01,8,rua 5 de março,6945,238525722,0
28,29,39906836380,raphael,morgado,2023-04-02,9,rua 3 de abril,9971,451487680,136366233
29,30,71047684176,renato,massamitsu,2023-04-03,9,rua São chico rico,2916,982133571,809927358
30,31,80872347461,roulien,roland,2023-04-04,10,rua de são tadeu,6885,239426075,0
31,32,20499652769,thaís,falcão,2023-04-05,10,avenida do sucesso,2050,169539037,994288632
32,33,63536060421,vitor,cavalcanti,2023-04-06,11,travessa da maria mariana,6609,587521150,54414341
33,34,43318780907,william,james,2023-04-07,11,rua da alegria,4573,535403160,596292484

### Exercício 1:

Faça uma query que retorne apenas os alunos de Curitiba (1);

In [13]:
ps.sqldf("""
SELECT
    id_cidade,
    primeiro_nome
FROM alunos
WHERE id_cidade = 1
LIMIT 10
""")

   id_cidade primeiro_nome
0          1        abelar
1          1       adriano
2          1        amanda
3          1        álvaro
4          1      henrique
5          1        hevans
6          1       isabela
7          1        kelvin

### Exercício 2:

Query que retorne apenas alunos que comecem com "R";

In [27]:
ps.sqldf("""
SELECT
  id_cidade,
  primeiro_nome
FROM
  alunos
WHERE
  primeiro_nome LIKE "r%"
""")

   id_cidade primeiro_nome
0          8        rafael
1          9       raphael
2          9        renato
3         10       roulien

### Exercício 3:

Query que retorne apenas alunos que entraram em março;

In [29]:
ps.sqldf("""
SELECT
  primeiro_nome,
  ultimo_nome,
  data_ingresso
FROM
  alunos
WHERE
  data_ingresso >= 2023-03-01
""")

   primeiro_nome ultimo_nome data_ingresso
0         abelar    henrique    2023-03-05
1        adriano    gambetta    2023-03-06
2         amanda      moulin    2023-03-07
3         álvaro     fonseca    2023-03-08
4          andre    melchior    2023-03-09
5        antonio     zanutto    2023-03-10
6       carolina        yumi    2023-03-11
7      christyan       costa    2023-03-12
8        claudia  cavalcante    2023-03-13
9      cristiane       nunes    2023-03-14
10        danilo      nozima    2023-03-15
11         diego   rodrigues    2023-03-16
12     emanuelle       lemos    2023-03-17
13       gabriel      mourão    2023-03-18
14       haroldo       silva    2023-03-19
15      henrique    guerrero    2023-03-20
16        hevans     pereira    2023-03-21
17       isabela       bueno    2023-03-22
18        kelvin   pichinini    2023-03-23
19         lucas   voltolini    2023-03-24
20       janaina     delgado    2023-03-25
21        manuel      castro    2023-03-26
22        marcio     magrini    2023-03-27
23        michel       souza    2023-03-28
24          mike    pessanha    2023-03-29
25         paula     ribeiro    2023-03-30
26         paula     marques    2023-03-31
27        rafael     ribeiro    2023-04-01
28       raphael     morgado    2023-04-02
29        renato  massamitsu    2023-04-03
30       roulien      roland    2023-04-04
31         thaís     falcão     2023-04-05
32         vitor  cavalcanti    2023-04-06
33       william       james    2023-04-07

### Exercício 4:

Query que retorne apenas alunos que tem 2 telefones;

In [14]:
ps.sqldf("""
SELECT
    primeiro_nome,
    telefone_a,
    telefone_b
FROM alunos
WHERE telefone_b != 0
""")

   primeiro_nome  telefone_a  telefone_b
0         abelar   866862753   274845545
1         amanda   872235320   911955261
2         álvaro   938535574   262020598
3          andre   189494206   323561018
4        antonio   379611062   919134470
5      christyan   845459713   615675266
6        claudia   202878321   603379305
7         danilo   374388553   328960508
8          diego   470084815   443097717
9        gabriel   478176185   573145168
10       haroldo   576548312   301677712
11        hevans   263674118   384972402
12       isabela   740040561   230351268
13         lucas   613900746   909322964
14       janaina   789048901   885432495
15        manuel   400549536     7115358
16        marcio   466204695    23079842
17        michel   827235134   314861183
18          mike   105333699   168590669
19       raphael   451487680   136366233
20        renato   982133571   809927358
21         thaís   169539037   994288632
22         vitor   587521150    54414341
23       william   535403160   596292484

### Exercício 5:

Query que retorne apenas alunos que tem 1 telefone apenas;

In [30]:
ps.sqldf("""
SELECT
  primeiro_nome,
  telefone_a,
  telefone_b
FROM
  alunos
WHERE
  telefone_b = 0
""")

  primeiro_nome  telefone_a  telefone_b
0       adriano   273807947           0
1      carolina   422505705           0
2     cristiane   708729599           0
3     emanuelle   326789195           0
4      henrique   639795496           0
5        kelvin   538617705           0
6         paula   819037434           0
7         paula   730517155           0
8        rafael   238525722           0
9       roulien   239426075           0

### Exercício 6:

Query que retorne apenas alunos com 1 telefone que moram em SP;

In [18]:
ps.sqldf("""
SELECT
  primeiro_nome,
  id_cidade,
  telefone_a,
  telefone_b
FROM
  alunos
WHERE
  telefone_b = 0
  AND id_cidade = 2
""")

  primeiro_nome  id_cidade  telefone_a  telefone_b
0      carolina          2   422505705           0

### Exercício 7:

Query que retorne apenas alunos com cod_cidade par;

In [ ]:
ps.sqldf("""
SELECT
  *
FROM
  alunos
WHERE
  id_cidade % 2 = 0
""")

### Exercício 8:

Query que retorne os 10 primeiros alunos que ingressaram em seus cursos;

In [33]:
ps.sqldf("""
SELECT
  primeiro_nome,
  ultimo_nome,
  data_ingresso
FROM
  alunos
ORDER BY
  data_ingresso ASC
LIMIT
  10
""")

  primeiro_nome ultimo_nome data_ingresso
0        abelar    henrique    2023-03-05
1       adriano    gambetta    2023-03-06
2        amanda      moulin    2023-03-07
3        álvaro     fonseca    2023-03-08
4         andre    melchior    2023-03-09
5       antonio     zanutto    2023-03-10
6      carolina        yumi    2023-03-11
7     christyan       costa    2023-03-12
8       claudia  cavalcante    2023-03-13
9     cristiane       nunes    2023-03-14

### Exercício 9:

Query que retorne apenas os 10 ultimos alunos ingressantes;

In [34]:
ps.sqldf("""
SELECT
  primeiro_nome,
  ultimo_nome,
  data_ingresso
FROM
  alunos
ORDER BY
  data_ingresso DESC
LIMIT
  10
""")

  primeiro_nome ultimo_nome data_ingresso
0       william       james    2023-04-07
1         vitor  cavalcanti    2023-04-06
2         thaís     falcão     2023-04-05
3       roulien      roland    2023-04-04
4        renato  massamitsu    2023-04-03
5       raphael     morgado    2023-04-02
6        rafael     ribeiro    2023-04-01
7         paula     marques    2023-03-31
8         paula     ribeiro    2023-03-30
9          mike    pessanha    2023-03-29

### Exercício 10:

Query que retorne apenas os alunos que moram em casas de 3 dígitos;

In [25]:
ps.sqldf("""
SELECT
  cpf,
  primeiro_nome,
  numero,
  CAST(numero AS text) AS numero_texto,
  LENGTH(CAST(numero AS text)) AS digitos
FROM
  alunos
WHERE
  LENGTH(CAST(numero AS text)) = 3
""")

           cpf primeiro_nome  numero numero_texto  digitos
0  87486965183        manuel     582          582        3
1  46927680338        marcio     239          239        3

### Exercício 11:

Query que retorne apenas as cidades com estado maiusculo;

In [36]:
cidades = pd.read_csv("/content/drive/MyDrive/ADA_Braskem/Curso/3-[DS-PY-006] BANCO DE DADOS I/base_curso/cidades.csv")
ps.sqldf("""
SELECT
  cidade,
  estado
FROM
  cidades
""")

          cidade estado
0       curitiba     PR
1      sao paulo     SP
2       salvador     BA
3         jequié     BA
4     tiradentes     mg
5     uberlandia     MG
6      congonhas     MG
7    porto velho     RO
8           jaru     RO
9   alto paraíso     RO
10    ouro preto     MG

### Exercício 12:

Query que retorne apenas cidades com 7 ou mais letras no nome;

In [42]:
ps.sqldf("""
SELECT
  *
FROM
  cidades
WHERE
  LENGTH(CAST(cidade AS text)) >= 7
""")

   id_cidade        cidade estado
0          1      curitiba     PR
1          2     sao paulo     SP
2          3      salvador     BA
3          5    tiradentes     mg
4          6    uberlandia     MG
5          7     congonhas     MG
6          8   porto velho     RO
7         10  alto paraíso     RO
8         11    ouro preto     MG

### Exercício 13:

Query que retorne apenas alunos que moram em cidades com 7 ou mais letras;

In [52]:
ps.sqldf("""
SELECT
  A.primeiro_nome,
  A.ultimo_nome,
  C.cidade,
  C.estado
FROM
  alunos AS A
  LEFT JOIN cidades AS C
  ON A.id_cidade = C.id_cidade
WHERE
  LENGTH(CAST(cidade AS text)) >= 7
""")

   primeiro_nome ultimo_nome        cidade estado
0         abelar    henrique      curitiba     PR
1        adriano    gambetta      curitiba     PR
2         amanda      moulin      curitiba     PR
3         álvaro     fonseca      curitiba     PR
4          andre    melchior     sao paulo     SP
5        antonio     zanutto     sao paulo     SP
6       carolina        yumi     sao paulo     SP
7      christyan       costa     sao paulo     SP
8        claudia  cavalcante      salvador     BA
9      cristiane       nunes      salvador     BA
10        danilo      nozima      salvador     BA
11         diego   rodrigues      salvador     BA
12      henrique    guerrero      curitiba     PR
13        hevans     pereira      curitiba     PR
14       isabela       bueno      curitiba     PR
15        kelvin   pichinini      curitiba     PR
16         lucas   voltolini    tiradentes     mg
17       janaina     delgado    uberlandia     MG
18        manuel      castro    uberlandia     MG
19        marcio     magrini     congonhas     MG
20        michel       souza     congonhas     MG
21          mike    pessanha     congonhas     MG
22         paula     ribeiro   porto velho     RO
23         paula     marques   porto velho     RO
24        rafael     ribeiro   porto velho     RO
25       roulien      roland  alto paraíso     RO
26         thaís     falcão   alto paraíso     RO
27         vitor  cavalcanti    ouro preto     MG
28       william       james    ouro preto     MG

### Exercício 14:

Query que retorne apenas alunos com primeira letra do nome e do sobrenome sendo vogais;

In [54]:
ps.sqldf("""
SELECT
  primeiro_nome,
  ultimo_nome
FROM
  alunos
WHERE
  (
  primeiro_nome LIKE "a%" OR
  primeiro_nome LIKE "e%" OR
  primeiro_nome LIKE "i%" OR
  primeiro_nome LIKE "o%" OR
  primeiro_nome LIKE "u%"
  )
  AND
  (
  ultimo_nome LIKE "a%" OR
  ultimo_nome LIKE "e%" OR
  ultimo_nome LIKE "i%" OR
  ultimo_nome LIKE "o%" OR
  ultimo_nome LIKE "u%"
  )
""")

  primeiro_nome ultimo_nome
0     christyan       costa
1       claudia  cavalcante

### Exercício 15:

Query que retorne apenas Baianos com nomes com mais de 4 letras;

In [58]:
ps.sqldf("""
SELECT
  A.primeiro_nome,
  A.ultimo_nome,
  C.cidade,
  C.estado
FROM
  alunos AS A
  LEFT JOIN cidades AS C
  ON A.id_cidade = C.id_cidade
WHERE
  estado LIKE "BA"
""")

  primeiro_nome ultimo_nome    cidade estado
0       claudia  cavalcante  salvador     BA
1     cristiane       nunes  salvador     BA
2        danilo      nozima  salvador     BA
3         diego   rodrigues  salvador     BA
4     emanuelle       lemos    jequié     BA
5       gabriel      mourão    jequié     BA
6       haroldo       silva    jequié     BA